services:
#  seplag-api:
#    image: seplag-api:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/seplag
#      - SPRING_DATASOURCE_USERNAME=admin
#      - SPRING_DATASOURCE_PASSWORD=admin
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - MINIO_URL=http://minio:9000
#    depends_on:
#      - postgres
#       - minio:
#          condition: service_healthy
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=seplag'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5433:5432'
  minio:
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  minio-data:

